language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ikemole/react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ikemole/react-client-test npm test

after_success:
  - docker build -t ikemole/multi-client ./client
  - docker build -t ikemole/multi-nginx ./nginx
  - docker build -t ikemole/multi-server ./server
  - docker build -t ikemole/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push ikemole/multi-client
  - docker push ikemole/multi-nginx
  - docker push ikemole/multi-server
  - docker push ikemole/multi-worker
